version: '3.8'

services:
  llm-deployment-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-deployment-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - WORKER_SECRET=${WORKER_SECRET}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_USER_OR_ORG=${GITHUB_USER_OR_ORG}
      - NODE_ENV=production
    volumes:
      # Mount logs directory (optional)
      - ./logs:/app/logs
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge

# Usage:
# 1. Copy .env.example to .env and fill in values
# 2. Run: docker-compose up -d
# 3. View logs: docker-compose logs -f
# 4. Stop: docker-compose down
